### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by Bibii156** [dynamo58/twitch-bot#1]
Hello,
I'm just trying to host your bot because I'm bored.
I have some errors, what did I miss?
[pastebin](https://pastebin.com/X3jkVP3u)
I'm Pepega sorry.

**Comment by dynamo58** [comment]
Oh yeah about that....
I am sorry for that. I was too lazy to create a new branch. But I had to exit the workspace I was working from, so I commited some half-assed code. If you revert to [this](https://github.com/dynamo58/twitch-bot/commit/abfce49e458fb645c8d324f9ca8d03f7900a240a) commit, everything should work.

**Comment by Bibii156** [comment]
thank you!
